In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
##########################Q1 Assignment 1-B#########################

path = r'C:\Users\udit sharma\Desktop\Aut\Data Mining and Machine Learning\Data sets Assignment 1\Forest.xlsx'
rawdata = pd.read_excel(path) #Read the data set
rawdata.head()

class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0    d   39  36  57   91  59  101   93  27  60  ...                -2.36   
1    h   84  30  57  112  51   98   92  26  62  ...                -2.26   
2    s   53  25  49   99  51   93   84  26  58  ...                -1.46   
3    s   59  26  49  103  47   92   82  25  56  ...                 2.68   
4    d   57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18   
1               -18.79                -1.99                -6.18   
2               -17.73                -0.48                -4.69   
3               -22.03                -2.34                -6.60   
4               -23.74                -0.85                -5.50   

   pred_minus_obs_S_b7  pred_minus_obs_S_b8  pred_minus_obs_S_b9  
0               -22.50                -5.20                -7.86  
1               -23.41                -8.87               -10.83  
2               -19.97                -4.10                -7.07  
3               -27.10                -7.99               -10.81  
4               -22.83                -2.74                -5.84  

[5 rows x 28 columns]

In [2]:
class_target=rawdata.iloc[:,0]
nrow, ncol = rawdata.shape
label_encoder = LabelEncoder()
rawdata['class']= label_encoder.fit_transform(rawdata['class']) 
#Label encode the dataset for Classifier Use
rawdata.head()

class  b1  b2  b3   b4  b5   b6   b7  b8  b9  ...  pred_minus_obs_H_b9  \
0      0  39  36  57   91  59  101   93  27  60  ...                -2.36   
1      1  84  30  57  112  51   98   92  26  62  ...                -2.26   
2      3  53  25  49   99  51   93   84  26  58  ...                -1.46   
3      3  59  26  49  103  47   92   82  25  56  ...                 2.68   
4      0  57  49  66  103  64  106  114  28  59  ...                -2.94   

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.41                -1.88                -6.43   
1               -16.27                -1.95                -6.25   
2               -15.92                -1.79                -4.64   
3               -13.77                -2.53                -6.34   
4               -21.74                -1.64                -4.62   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -21.03                -1.60                -6.18   
1               -18.79                -1.99                -6.18   
2               -17.73                -0.48                -4.69   
3               -22.03                -2.34                -6.60   
4               -23.74                -0.85                -5.50   

   pred_minus_obs_S_b7  pred_minus_obs_S_b8  pred_minus_obs_S_b9  
0               -22.50                -5.20                -7.86  
1               -23.41                -8.87               -10.83  
2               -19.97                -4.10                -7.07  
3               -27.10                -7.99               -10.81  
4               -22.83                -2.74                -5.84  

[5 rows x 28 columns]

In [3]:
predictors=rawdata.iloc[:,1:ncol]
target=rawdata.iloc[:,0]
#Split the train test data into 70% and 30%
pred_train, pred_test, tar_train, tar_test  = train_test_split(predictors,target,test_size=.3,shuffle=False) 

In [5]:
##################### Q1 Part 1 ###########################

#########################################################
#----Decision Tree Classifier------
##########################################
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, auc

print('Below is the output for decision tree classifier')
DTclassifier = DecisionTreeClassifier(max_depth=3)  # configure the classifier
DTclassifier = DTclassifier.fit(pred_train, tar_train)  # train a decision tree model
predictionsDT = DTclassifier.predict(pred_test)  # deploy model and make predictions on test set
print("Accuracy score of our model with Decision Tree:", accuracy_score(tar_test, predictionsDT))
precision = precision_score(y_true=tar_test, y_pred=predictionsDT, average='micro')
print("Precision score of our model with Decision Tree :", precision)
recall = recall_score(y_true=tar_test, y_pred=predictionsDT, average='micro')
print("Recall score of our model with Decision Tree :", recall)

Below is the output for decision tree classifier
Accuracy score of our model with Decision Tree: 0.802547770700637
Precision score of our model with Decision Tree : 0.802547770700637
Recall score of our model with Decision Tree : 0.802547770700637


In [8]:
####################################################
#----------Multilayer Preceptron---------
##############################################
from sklearn.neural_network import MLPClassifier

MLPclassifier = MLPClassifier(learning_rate='constant',activation='logistic',solver='sgd',max_iter=4000,
                              learning_rate_init=0.001) # declare MLP classifier
MLPclassifier.fit(pred_train,np.ravel(tar_train,order='C')) # train MLP classifier
predictionsMLP = MLPclassifier.predict(pred_test)
print("Accuracy score of our model with MLP :", accuracy_score(tar_test, predictionsMLP))
scores = cross_val_score(MLPclassifier, predictors, target, cv=10)
print("Accuracy score of our model with MLP under cross validation :", scores.mean())

Accuracy score of our model with MLP : 0.8471337579617835
Accuracy score of our model with MLP under cross validation : 0.9098330914368651


In [9]:
#####################Confusion Matrix###############
from sklearn.metrics import confusion_matrix

#---Decision Tree Confusion Matrix----------
print('Confusion matrix for Decision Tree:')
cmDT=confusion_matrix(predictionsDT,tar_test)
print(cmDT)

#---MLP Classifier Confusion Matrix---------
print('Confusion Matrix for MLP Classifier:')
cmMLP=confusion_matrix(tar_test,predictionsMLP)
print(cmMLP)

Confusion matrix for Decision Tree:
[[40  1  4  8]
 [ 0 14  0  0]
 [ 2  0 10  0]
 [ 7  8  1 62]]
Confusion Matrix for MLP Classifier:
[[42  0  6  1]
 [ 0 15  0  8]
 [ 4  0 11  0]
 [ 4  1  0 65]]


In [11]:
######################### Q1 Part 2 #######################
#-------Part a------------------
probDT = DTclassifier.predict_proba(pred_test)  # obtain probability scores for Decision Tree Classifier
probMLP=MLPclassifier.predict_proba(pred_test)  #obtain probability scores for MLP classifier

for i in range(len(probDT)):
 print(probDT[i],probMLP[i])

[0.03225806 0.04032258 0.         0.92741935] [0.12061629 0.00537129 0.00652109 0.86749133]
[0.03225806 0.04032258 0.         0.92741935] [0.02653227 0.26487297 0.01203192 0.69656284]
[0.03225806 0.04032258 0.         0.92741935] [0.06154484 0.00677615 0.00435158 0.92732743]
[0.01694915 0.         0.98305085 0.        ] [0.01215544 0.00174868 0.98298114 0.00311474]
[0.89189189 0.01801802 0.08108108 0.00900901] [0.96564308 0.00218439 0.02284552 0.009327  ]


In [12]:
#-------------Part b------------------
from tabulate import tabulate
proba1=[]
s1 = ['d','h','o','s']
for i in range(4):
 prob2=[s1[i],probDT[0][i],probMLP[0][i]]
 proba1.append(prob2)

print(tabulate(proba1, headers=['Class', 'Decision Tree Classifier','MLP Classifier']))

Class      Decision Tree Classifier    MLP Classifier
-------  --------------------------  ----------------
d                         0.0322581        0.120616
h                         0.0403226        0.00537129
o                         0                0.00652109
s                         0.927419         0.867491


In [13]:
######################## Q1 Part 4 ###########

#########################################
#-----Average Aggregate Classifier Function
#########################################

def avgClassifier(pred_train,tar_train,pred_test):  

 classifier = DecisionTreeClassifier(max_depth=3)  # configure the Decision classifier
 classifier = classifier.fit(pred_train, tar_train)  # train a decision tree model
 probDT = classifier.predict_proba(pred_test)

 clf = MLPClassifier(learning_rate='constant', activation='logistic', solver='sgd', max_iter=4000,
                     learning_rate_init=0.001) # configure the MLP classifier
 clf.fit(pred_train, np.ravel(tar_train, order='C')) # train MLP classifier
 probMLP = clf.predict_proba(pred_test)
    
 avg_predictions=[]
 avg_prob = (probDT + probMLP) / 2
 max_avg_pred=0
 for i in range(len(pred_test)):
  l=[avg_prob[i][0],avg_prob[i][1],avg_prob[i][2],avg_prob[i][3]]
  max_avg_pred=l.index(max(l))
  avg_predictions.append(max_avg_pred)
  # print(max_avg_pred,avg_prob[i])
 return avg_predictions

#------Run the Average Aggregate Function--------
avg_predictions=avgClassifier(pred_train,tar_train,pred_test)
# print(avg_predictions)
print('The accuracy of the Average Aggregate Classifier is:',accuracy_score(tar_test,avg_predictions))

The accuracy of the Average Aggregate Classifier is: 0.821656050955414


In [14]:
######################## Q1 Part 6 #####################
#########################################
#----Conditional Probability Classifier Function
#########################################


def conditionalClassifier(pred_train,tar_train,pred_test,tar_test):
 
 ##############p(a/b)=p(a&b)/p(b) then p(class=s|Dt=s)=p(class=s&DT=s)/p(DT=s)

 #---DT Classifier-------------------
 classifier = DecisionTreeClassifier(max_depth=3)  # configure the classifier
 classifier = classifier.fit(pred_train, tar_train)  # train a decision tree model
 predictionsDT = classifier.predict(pred_test)  # deploy model and make predictions on test set
 probDT = classifier.predict_proba(pred_test)

 cmDT = confusion_matrix(tar_test,predictionsDT)
 condProbDT=[]
 for i in range(4):
  sumDT = 0
  for j in range(4):
   sumDT += cmDT[j][i]
  condProbDT.append(cmDT[i][i]/sumDT)


 #---MLP Classifier-------------
 clf = MLPClassifier(learning_rate='constant', activation='logistic', solver='sgd', max_iter=4000,
                     learning_rate_init=0.001)
 clf.fit(pred_train, np.ravel(tar_train, order='C'))
 predictionsMLP = clf.predict(pred_test)
 probMLP = clf.predict_proba(pred_test)
 cmMLP = confusion_matrix(tar_test, predictionsMLP)
 # print(cmMLP)
 condProbMLP=[]
 for i in range(4):
  sumMLP=0
  for j in range(4):
   sumMLP+=cmMLP[j][i]
  condProbMLP.append(cmMLP[i][i]/sumMLP)
  # l=cmMLP[:][i]
  # print(cmMLP[:][i],cmMLP[i][:])
  # print("abcasdasdsa",sum(cmMLP[:][i]),sumMLP,sum(l))
 
 #---Conditional Probability classifier----
 condProb=[]
 for i in range(len(predictionsDT)):
  if(probDT[i][predictionsDT[i]]*condProbDT[predictionsDT[i]]>probMLP[i][predictionsMLP[i]]*condProbMLP[predictionsMLP[i]]):
   condProb.append(predictionsDT[i])
  else:
   condProb.append(predictionsMLP[i])

 return condProb

#------Run the Conditional Probability Function--------
conditional_Predicitions=conditionalClassifier(pred_train,tar_train,pred_test,tar_test)
# print(conditional_Predicitions)
print('The accuracy of the Conditional Classifier is:',accuracy_score(tar_test,conditional_Predicitions))

The accuracy of the Conditional Classifier is: 0.8535031847133758
